/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    ColorPicker: typeof import('./../components/ColorPicker.vue')['default']
    IMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IMdiChartBar: typeof import('~icons/mdi/chart-bar')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiCog: typeof import('~icons/mdi/cog')['default']
    IMdiDelete: typeof import('~icons/mdi/delete')['default']
    IMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal')['default']
    IMdiFormatListBulleted: typeof import('~icons/mdi/format-list-bulleted')['default']
    IMdiGift: typeof import('~icons/mdi/gift')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiHelpCircle: typeof import('~icons/mdi/help-circle')['default']
    IMdiNetflix: typeof import('~icons/mdi/netflix')['default']
    IMdiTransitConnectionVariant: typeof import('~icons/mdi/transit-connection-variant')['default']
    IPhGlobe: typeof import('~icons/ph/globe')['default']
    IPhMoon: typeof import('~icons/ph/moon')['default']
    IPhSun: typeof import('~icons/ph/sun')['default']
    LocaleSwitch: typeof import('./../components/LocaleSwitch.vue')['default']
    OpenSettingsButton: typeof import('./../components/OpenSettingsButton.vue')['default']
    OptionalPermission: typeof import('./../components/OptionalPermission.vue')['default']
    OptionsPageSettingsTable: typeof import('./../components/options-page/SettingsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SharedPagesAmazon: typeof import('./../components/shared-pages/Amazon.vue')['default']
    SharedPagesCrunchyroll: typeof import('./../components/shared-pages/Crunchyroll.vue')['default']
    SharedPagesDisney: typeof import('./../components/shared-pages/Disney.vue')['default']
    SharedPagesNetflix: typeof import('./../components/shared-pages/Netflix.vue')['default']
    SharedPagesStatistics: typeof import('./../components/shared-pages/Statistics.vue')['default']
    Switch: typeof import('./../components/Switch.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
  }
}
