/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/action-popup/': RouteRecordInfo<'/action-popup/', '/action-popup', Record<never, never>, Record<never, never>>,
    '/action-popup/Amazon': RouteRecordInfo<'/action-popup/Amazon', '/action-popup/Amazon', Record<never, never>, Record<never, never>>,
    '/action-popup/Crunchyroll': RouteRecordInfo<'/action-popup/Crunchyroll', '/action-popup/Crunchyroll', Record<never, never>, Record<never, never>>,
    '/action-popup/Disney': RouteRecordInfo<'/action-popup/Disney', '/action-popup/Disney', Record<never, never>, Record<never, never>>,
    '/action-popup/Netflix': RouteRecordInfo<'/action-popup/Netflix', '/action-popup/Netflix', Record<never, never>, Record<never, never>>,
    '/action-popup/SharedOptions': RouteRecordInfo<'/action-popup/SharedOptions', '/action-popup/SharedOptions', Record<never, never>, Record<never, never>>,
    '/action-popup/Statistics': RouteRecordInfo<'/action-popup/Statistics', '/action-popup/Statistics', Record<never, never>, Record<never, never>>,
    '/options-page/': RouteRecordInfo<'/options-page/', '/options-page', Record<never, never>, Record<never, never>>,
    '/options-page/Amazon': RouteRecordInfo<'/options-page/Amazon', '/options-page/Amazon', Record<never, never>, Record<never, never>>,
    '/options-page/Backup': RouteRecordInfo<'/options-page/Backup', '/options-page/Backup', Record<never, never>, Record<never, never>>,
    '/options-page/Changelog': RouteRecordInfo<'/options-page/Changelog', '/options-page/Changelog', Record<never, never>, Record<never, never>>,
    '/options-page/Crunchyroll': RouteRecordInfo<'/options-page/Crunchyroll', '/options-page/Crunchyroll', Record<never, never>, Record<never, never>>,
    '/options-page/disabledSettings': RouteRecordInfo<'/options-page/disabledSettings', '/options-page/disabledSettings', Record<never, never>, Record<never, never>>,
    '/options-page/Disney': RouteRecordInfo<'/options-page/Disney', '/options-page/Disney', Record<never, never>, Record<never, never>>,
    '/options-page/install': RouteRecordInfo<'/options-page/install', '/options-page/install', Record<never, never>, Record<never, never>>,
    '/options-page/Netflix': RouteRecordInfo<'/options-page/Netflix', '/options-page/Netflix', Record<never, never>, Record<never, never>>,
    '/options-page/SharedSettings': RouteRecordInfo<'/options-page/SharedSettings', '/options-page/SharedSettings', Record<never, never>, Record<never, never>>,
    '/options-page/Statistics': RouteRecordInfo<'/options-page/Statistics', '/options-page/Statistics', Record<never, never>, Record<never, never>>,
  }
}
