/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/action-popup/': RouteRecordInfo<
      '/action-popup/',
      '/action-popup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/action-popup/Amazon': RouteRecordInfo<
      '/action-popup/Amazon',
      '/action-popup/Amazon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/action-popup/Crunchyroll': RouteRecordInfo<
      '/action-popup/Crunchyroll',
      '/action-popup/Crunchyroll',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/action-popup/Disney': RouteRecordInfo<
      '/action-popup/Disney',
      '/action-popup/Disney',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/action-popup/Netflix': RouteRecordInfo<
      '/action-popup/Netflix',
      '/action-popup/Netflix',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/action-popup/SharedOptions': RouteRecordInfo<
      '/action-popup/SharedOptions',
      '/action-popup/SharedOptions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/action-popup/Statistics': RouteRecordInfo<
      '/action-popup/Statistics',
      '/action-popup/Statistics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/': RouteRecordInfo<
      '/options-page/',
      '/options-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/Amazon': RouteRecordInfo<
      '/options-page/Amazon',
      '/options-page/Amazon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/Backup': RouteRecordInfo<
      '/options-page/Backup',
      '/options-page/Backup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/Changelog': RouteRecordInfo<
      '/options-page/Changelog',
      '/options-page/Changelog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/Crunchyroll': RouteRecordInfo<
      '/options-page/Crunchyroll',
      '/options-page/Crunchyroll',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/disabledSettings': RouteRecordInfo<
      '/options-page/disabledSettings',
      '/options-page/disabledSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/Disney': RouteRecordInfo<
      '/options-page/Disney',
      '/options-page/Disney',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/install': RouteRecordInfo<
      '/options-page/install',
      '/options-page/install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/Netflix': RouteRecordInfo<
      '/options-page/Netflix',
      '/options-page/Netflix',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/SharedSettings': RouteRecordInfo<
      '/options-page/SharedSettings',
      '/options-page/SharedSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/options-page/Statistics': RouteRecordInfo<
      '/options-page/Statistics',
      '/options-page/Statistics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/ui/action-popup/pages/index.vue': {
      routes:
        | '/action-popup/'
      views:
        | never
    }
    'src/ui/action-popup/pages/Amazon.vue': {
      routes:
        | '/action-popup/Amazon'
      views:
        | never
    }
    'src/ui/action-popup/pages/Crunchyroll.vue': {
      routes:
        | '/action-popup/Crunchyroll'
      views:
        | never
    }
    'src/ui/action-popup/pages/Disney.vue': {
      routes:
        | '/action-popup/Disney'
      views:
        | never
    }
    'src/ui/action-popup/pages/Netflix.vue': {
      routes:
        | '/action-popup/Netflix'
      views:
        | never
    }
    'src/ui/action-popup/pages/SharedOptions.vue': {
      routes:
        | '/action-popup/SharedOptions'
      views:
        | never
    }
    'src/ui/action-popup/pages/Statistics.vue': {
      routes:
        | '/action-popup/Statistics'
      views:
        | never
    }
    'src/ui/options-page/pages/index.vue': {
      routes:
        | '/options-page/'
      views:
        | never
    }
    'src/ui/options-page/pages/Amazon.vue': {
      routes:
        | '/options-page/Amazon'
      views:
        | never
    }
    'src/ui/options-page/pages/Backup.vue': {
      routes:
        | '/options-page/Backup'
      views:
        | never
    }
    'src/ui/options-page/pages/Changelog.vue': {
      routes:
        | '/options-page/Changelog'
      views:
        | never
    }
    'src/ui/options-page/pages/Crunchyroll.vue': {
      routes:
        | '/options-page/Crunchyroll'
      views:
        | never
    }
    'src/ui/options-page/pages/disabledSettings.vue': {
      routes:
        | '/options-page/disabledSettings'
      views:
        | never
    }
    'src/ui/options-page/pages/Disney.vue': {
      routes:
        | '/options-page/Disney'
      views:
        | never
    }
    'src/ui/options-page/pages/install.vue': {
      routes:
        | '/options-page/install'
      views:
        | never
    }
    'src/ui/options-page/pages/Netflix.vue': {
      routes:
        | '/options-page/Netflix'
      views:
        | never
    }
    'src/ui/options-page/pages/SharedSettings.vue': {
      routes:
        | '/options-page/SharedSettings'
      views:
        | never
    }
    'src/ui/options-page/pages/Statistics.vue': {
      routes:
        | '/options-page/Statistics'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
