/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    IMdiCog: typeof import('~icons/mdi/cog')['default']
    IMdiGift: typeof import('~icons/mdi/gift')['default']
    IPhArrowLeft: typeof import('~icons/ph/arrow-left')['default']
    IPhGlobe: typeof import('~icons/ph/globe')['default']
    IPhMoon: typeof import('~icons/ph/moon')['default']
    IPhSun: typeof import('~icons/ph/sun')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    LocaleSwitch: typeof import('./../components/LocaleSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    Switch: typeof import('./../components/Switch.vue')['default']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
  }
}
